import { Schema, model } from "mongoose";

const timetableSchema = new Schema(
  {
    timetable_id: {
      type: String,
      required: [true, "Timetable ID is required"],
      unique: true,
      uppercase: true,
      trim: true,
    },
    semester_id: {
      type: String,
      required: [true, "Semester ID is required"],
      uppercase: true,
      trim: true,
    },
    academicYear: {
      type: String,
      required: [true, "Academic year is required"],
      uppercase: true,
      trim: true,
    },
    generated_date: {
      type: Date,
      default: Date.now,
    },
    generatedBy: {
      type: String,
      required: [true, "Generated by is required"],
      uppercase: true,
      trim: true,
    },
    status: {
      type: String,
      enum: ["draft", "published", "archived"],
      default: "draft",
    },
    entries: {
      type: Array,
      default: [],
    },
  },
  { timestamps: true },
);

export const Timetable = model("Timetable", timetableSchema);
