import React, { useEffect, useState } from "react";

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const PERIODS = ["1", "2", "3", "4", "5", "6", "7", "8"];

export default function Student() {
  const [masterData, setMasterData] = useState(null);
  const [timetables, setTimetables] = useState(null);
  const [selectedClass, setSelectedClass] = useState("");
  const [selectedSection, setSelectedSection] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      try {
        const classRes = await fetch("http://localhost:5000/api/v1/classes").then(r => r.json());
        const sectionRes = await fetch("http://localhost:5000/api/v1/sections").then(r => r.json());
        const subjectRes = await fetch("http://localhost:5000/api/v1/subjects").then(r => r.json());
        const facultyRes = await fetch("http://localhost:5000/api/v1/faculty").then(r => r.json());
        const ttRes = await fetch("http://localhost:5000/api/v1/timetable").then(r => r.json());

        setMasterData({
          class: classRes.data || [],
          section: sectionRes.data || [],
          subject: subjectRes.data || [],
          faculty: facultyRes.data || []
        });

        // Group the API timetable response into a Class -> Grid map
        const ttMap = {};
        if (ttRes?.data) {
          ttRes.data.forEach(item => {
            const classCode = item.class_id;
            if (!ttMap[classCode]) ttMap[classCode] = { classCode, grid: {} };

            const day = item.day_of_week;
            const period = item.time_slot;
            if (!ttMap[classCode].grid[day]) ttMap[classCode].grid[day] = {};

            ttMap[classCode].grid[day][period] = {
              subjectCode: item.subject_id,
              facultyId: item.faculty_id,
              room: item.room_id
            };
          });
        }
        setTimetables(ttMap);

      } catch (err) {
        console.error("Error fetching student timetable:", err);
        setMasterData({});
        setTimetables({});
      }
    };

    fetchData();
  }, []);

  if (!masterData || !timetables) {
    return (
      <div className="text-sm text-gray-600">
        Loading timetable data from admin...
      </div>
    );
  }

  const classList = masterData.class || [];
  const sectionList = (masterData.section || []).filter(
    (s) => !selectedClass || s.classCode === selectedClass
  );

  const currentTimetable = selectedClass ? timetables[selectedClass] : null;

  const getSubjectLabel = (subjectCode) => {
    if (!subjectCode) return "";
    const subjects = masterData.subject || [];
    const match =
      subjects.find((s) => s.code === subjectCode) ||
      subjects.find((s) => s.name === subjectCode);
    if (!match) return subjectCode;
    return `${match.code} - ${match.name}`;
  };

  const getFacultyLabel = (facultyId) => {
    if (!facultyId) return "";
    const list = masterData.faculty || [];
    const match = list.find((f) => f.employeeId === facultyId);
    if (!match) return facultyId;
    return `${match.name} (${match.employeeId})`;
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">
            Student Timetable
          </h1>
          <p className="text-xs text-gray-500">
            View read-only class timetable generated by admin.
          </p>
        </div>
      </div>

      {!classList.length && (
        <div className="border border-dashed border-gray-300 rounded-xl p-4 text-sm text-gray-500">
          No classes found. Please contact admin to create classes and
          timetables.
        </div>
      )}

      {classList.length > 0 && (
        <>
          <div className="flex flex-wrap gap-4 items-end">
            <div className="space-y-1">
              <label className="text-xs font-medium text-gray-700">
                Select class
              </label>
              <select
                value={selectedClass}
                onChange={(e) => {
                  setSelectedClass(e.target.value);
                  setSelectedSection("");
                }}
                className="px-3 py-2 text-sm border border-gray-300 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                <option value="">Choose class</option>
                {classList.map((cls) => (
                  <option key={cls.id} value={cls.code}>
                    {cls.code} ({cls.batchName})
                  </option>
                ))}
              </select>
            </div>

            {sectionList.length > 0 && (
              <div className="space-y-1">
                <label className="text-xs font-medium text-gray-700">
                  Section (optional)
                </label>
                <select
                  value={selectedSection}
                  onChange={(e) => setSelectedSection(e.target.value)}
                  className="px-3 py-2 text-sm border border-gray-300 rounded-lg bg-white focus:outline-none focus:ring-2 focus:ring-indigo-500"
                >
                  <option value="">All sections</option>
                  {sectionList.map((sec) => (
                    <option key={sec.id} value={sec.name}>
                      {sec.name}
                    </option>
                  ))}
                </select>
              </div>
            )}
          </div>

          {!selectedClass && (
            <div className="border border-dashed border-gray-300 rounded-xl p-4 text-xs text-gray-500">
              Choose your class to view the timetable.
            </div>
          )}

          {selectedClass && !currentTimetable && (
            <div className="border border-dashed border-yellow-300 rounded-xl p-4 text-xs text-yellow-700 bg-yellow-50">
              No timetable found for this class. Please contact admin.
            </div>
          )}

          {selectedClass && currentTimetable && (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="text-sm text-gray-700">
                  Timetable for{" "}
                  <span className="font-semibold">{selectedClass}</span>
                  {selectedSection && (
                    <span>
                      {" "}
                      – Section <span className="font-semibold">{selectedSection}</span>
                    </span>
                  )}
                </div>
              </div>

              <div className="overflow-x-auto rounded-lg border border-gray-200 bg-white max-h-[520px]">
                <table className="min-w-full text-xs">
                  <thead className="bg-gray-100 sticky top-0 z-10">
                    <tr>
                      <th className="px-2 py-2 text-left font-semibold text-gray-700">
                        Day / Period
                      </th>
                      {PERIODS.map((p) => (
                        <th
                          key={p}
                          className="px-2 py-2 text-center font-semibold text-gray-700"
                        >
                          {p}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {DAYS.map((day) => (
                      <tr key={day} className="border-t border-gray-100">
                        <td className="px-2 py-2 text-xs font-medium text-gray-700 whitespace-nowrap bg-gray-50">
                          {day}
                        </td>
                        {PERIODS.map((p) => {
                          const cell = currentTimetable.grid?.[day]?.[p] || {};
                          const hasAny =
                            cell.subjectCode || cell.facultyId || cell.room;
                          return (
                            <td
                              key={p}
                              className={`px-2 py-2 align-top min-w-[160px] ${hasAny ? "bg-white" : "bg-gray-50"
                                }`}
                            >
                              {hasAny ? (
                                <div className="space-y-0.5">
                                  {cell.subjectCode && (
                                    <div className="font-medium text-[11px] text-gray-900">
                                      {getSubjectLabel(cell.subjectCode)}
                                    </div>
                                  )}
                                  {cell.facultyId && (
                                    <div className="text-[11px] text-gray-600">
                                      {getFacultyLabel(cell.facultyId)}
                                    </div>
                                  )}
                                  {cell.room && (
                                    <div className="text-[10px] text-gray-400">
                                      Room: {cell.room}
                                    </div>
                                  )}
                                </div>
                              ) : (
                                <div className="text-[10px] text-gray-300 text-center">
                                  Free
                                </div>
                              )}
                            </td>
                          );
                        })}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
